# Generated by Django 3.2.9 on 2021-11-29 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_dealerships'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dealerships',
        ),
    ]
