# Generated by Django 3.2.9 on 2021-11-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_dealership_zipcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealership',
            name='id',
        ),
        migrations.AlterField(
            model_name='dealership',
            name='ids',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ids'),
        ),
    ]
