# Generated by Django 3.2.9 on 2021-11-29 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_dealership_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealership',
            name='zipCode',
            field=models.IntegerField(verbose_name='zipCode'),
        ),
    ]
