# Generated by Django 3.2.9 on 2021-11-29 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_dealership_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealership',
            name='zipCode',
            field=models.CharField(max_length=15, verbose_name='zipCode'),
        ),
    ]
