# Generated by Django 3.2.9 on 2021-11-29 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_dealership_zipcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dealership',
        ),
    ]
