# Generated by Django 3.2.9 on 2021-11-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_delete_dealership'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('ids', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='ids')),
                ('dealersName', models.TextField(verbose_name='DealersName')),
                ('address', models.TextField(verbose_name='Address')),
                ('state', models.CharField(max_length=5, verbose_name='state')),
                ('zipcode', models.BigIntegerField(verbose_name='zipcode')),
            ],
        ),
    ]
