# Generated by Django 3.2.9 on 2021-11-29 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_dealer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dealer',
        ),
    ]
