# Generated by Django 3.2.9 on 2021-12-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_userpost_zipcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carID', models.IntegerField(verbose_name='Column1')),
                ('price', models.IntegerField(verbose_name='Column2')),
                ('msrp', models.IntegerField(verbose_name='Column3')),
                ('mileage', models.IntegerField(verbose_name='Column4')),
                ('new', models.BooleanField(default=True, verbose_name='Column5')),
                ('model', models.CharField(max_length=20, verbose_name='Column6')),
                ('make', models.CharField(max_length=20, verbose_name='Column7')),
                ('year', models.IntegerField(verbose_name='Column8')),
                ('dealerID', models.IntegerField(verbose_name='Column9')),
            ],
        ),
        migrations.AlterField(
            model_name='userpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pics'),
        ),
    ]
